version: '3.4'

volumes: 
  pgData:

services: 
  pg:
    container_name: pg
    image: postgis/postgis:11-3.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=catenary
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - pgData:/var/lib/postgresql/data